ekf_node:
  ros__parameters:
    frequency: 400.0  # Filter update rate (Hz)
    # use_sim_time: true
    
    # Sensor input sources
    two_d_mode: true  # If the robot operates in a planar environment
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom # Change to "map" if fusing absolute position (e.g., GPS)
    publish_tf: true
    
    # Sensor fusion (set true for sources you are using)
    odom0: diff_cont/odom
    odom0_config: [false, false, false,  # X, Y, Z
                   false, false, false,  # Roll, Pitch, Yaw
                   true, true, false,    # X', Y', Z'
                   false, false, false,  # Roll', Pitch', Yaw'
                   false, false, false]  # Acceleration

    imu0: imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_differential: true
    imu0_remove_gravitational_acceleration: true